# Variables:
#vars:
#  firebase-project-id: "nuxt-apollo-hasura"

version: '3.6'
services:
  postgres:
    container_name: erd-postgres
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PRODUCTION_PRORGES_PASSWORD:-postgrespassword}

  graphql-engine:
    container_name: erd-hasura
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '4000:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PRODUCTION_PRORGES_USER:-postgres}:${PRODUCTION_PRORGES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_ADMIN_SECRET: ${PRODUCTION_HASURA_GRAPHQL_ADMIN_SECRET:-adminpassword}

volumes:
  db_data:
